"""Structure builders for aiida-uranium-workflow."""

from __future__ import annotations

from .common import STATIC_DIR
from .yamlio import read_yaml
from typing import Any
from pathlib import Path

import argparse
import sys

STRUCTURE_YML = STATIC_DIR / "structure.yml"


def build_structure(atom_name: str, *, registry: dict[str, Any] | None = None):
    """Build an ASE Atoms object from a static entry via pyxtal.

    Returns
    -------
    ase.Atoms
        An ASE ``Atoms`` instance generated by ``pyxtal`` from the
        spacegroup / Wyckoff-position / lattice parameters declared in
        ``static/structure.yml``.

    Notes
    -----
    Uses ``pyxtal.pyxtal.from_spg_wps_rep``:
        from pyxtal import pyxtal
        cry = pyxtal()
        cry.from_spg_wps_rep(spg, wps, [a, x1, x2, ...], [species_per_wp])
        return cry.to_ase()

    ``elements`` is a per-Wyckoff-position species list (length must
    match ``wickoff_position``); ``x`` packs one lattice parameter
    followed by fractional coordinates for each Wyckoff site.
    """
    # Imports are deferred so this module is importable even without
    # heavy dependencies (ase / pyxtal) for code paths that only need
    # the YAML loader.
    from pyxtal import pyxtal

    if registry is None:
        registry = read_yaml(STRUCTURE_YML)

    if atom_name not in registry:
        raise KeyError(f"Structure '{atom_name}' not found in {STRUCTURE_YML}")
    entry = registry[atom_name]

    spg = int(entry["spacegroup"])
    # The YAML key is ``wickoff_position`` (typo-tolerant alias);
    # pyxtal expects ``wps`` (Wyckoff positions).
    wps = entry.get("wps") or entry.get("wickoff_position")
    if not wps:
        raise KeyError(f"Structure '{atom_name}' is missing 'wps' / 'wickoff_position'")

    elements = entry["elements"]
    if len(elements) != len(wps):
        raise ValueError(
            f"Structure '{atom_name}': 'elements' (len={len(elements)}) must "
            f"match 'wickoff_position' (len={len(wps)})"
        )

    x = entry["x"]
    # pyxtal accepts two layouts for the ``x`` 1D array:
    #   * ``[lat_const]``           — special Wyckoff positions only;
    #     fractional coords are inferred from the space group.
    #   * ``[lat_const, fx1,fy1,fz1, ...]`` — one triplet per Wyckoff
    #     site, used when the symmetry alone doesn't fix the coords.
    if not isinstance(x, list) or len(x) < 1 or (
        len(x) != 1 and (len(x) - 1) % 3 != 0
    ):
        raise ValueError(
            f"Structure '{atom_name}': 'x' must be either [lat_const_A] "
            f"or [lat_const_A, fx1, fy1, fz1, ...] "
            f"(got {len(x)} value(s) for {len(wps)} site(s))"
        )
    a = [float(v) for v in x]

    cry = pyxtal()
    cry.from_spg_wps_rep(spg, wps, a, list(elements))
    return cry.to_ase()


def write_cif(
    atom_name: str,
    output_dir: str | Path = ".",
    *,
    registry: dict[str, Any] | None = None,
) -> Path:
    """Build ``atom_name`` and write it to ``<output_dir>/<safe_name>.cif``.

    Structure keys may contain path separators (e.g. ``U-X/FCC``); these
    are rewritten to ``__`` so the resulting filename stays flat in
    ``output_dir``. ``U-X/FCC`` → ``U-X__FCC.cif``.

    Parameters
    ----------
    atom_name
        Key in ``static/structure.yml``.
    output_dir
        Directory the CIF file will be written to. Created if it does
        not exist.
    registry
        Optional pre-loaded structure registry (used by tests).

    Returns
    -------
    pathlib.Path
        Absolute path of the written ``.cif`` file.
    """
    import ase.io

    atoms = build_structure(atom_name, registry=registry)
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    safe_name = atom_name.replace("/", "__")
    out_path = (out_dir / safe_name).with_suffix(".cif").resolve()
    ase.io.write(str(out_path), atoms, format="cif")
    return out_path


def _build_arg_parser() -> argparse.ArgumentParser:
    """Build the CLI argument parser for :func:`main`."""
    p = argparse.ArgumentParser(
        prog="aiida-uranium-structure-cif",
        description=(
            "Generate CIF files for the structures registered in "
            "static/structure.yml."
        ),
    )
    p.add_argument(
        "names",
        nargs="*",
        default=[],
        help=(
            "One or more structure names as listed in static/structure.yml "
            "(e.g. 'bcc-uranium' 'bcc-uranium-0K'). Optional when --list is given."
        ),
    )
    p.add_argument(
        "-o",
        "--output-dir",
        dest="output_dir",
        default=".",
        help="Directory to write the .cif files into (default: current directory).",
    )
    p.add_argument(
        "--list",
        action="store_true",
        dest="list_only",
        help="List the registered structures and exit.",
    )
    return p


def main(argv: list[str] | None = None) -> int:
    """CLI entry point: build the requested structures and write CIF files.

    Examples
    --------
    Generate a single CIF file in the current directory::

        python -m aiida_uranium_workflow.utils.structure bcc-uranium

    Generate several CIF files in a specific directory::

        python -m aiida_uranium_workflow.utils.structure \\
            bcc-uranium bcc-uranium-0K -o ./cifs

    Inspect the registered structures without writing anything::

        python -m aiida_uranium_workflow.utils.structure --list
    """
    args = _build_arg_parser().parse_args(argv)
    registry = read_yaml(STRUCTURE_YML)

    if args.list_only:
        print("Available structures:")
        for name in registry:
            print(f"  - {name}")
        return 0

    if not args.names:
        print(
            "[structure] error: at least one structure name is required "
            "(use --list to inspect registered structures).",
            file=sys.stderr,
        )
        return 1

    written: list[Path] = []
    for name in args.names:
        try:
            path = write_cif(name, output_dir=args.output_dir, registry=registry)
        except (KeyError, ValueError, NotImplementedError) as exc:
            print(f"[structure] error: {exc}", file=sys.stderr)
            return 1
        print(f"[structure] wrote {path}")
        written.append(path)

    if not written:
        print("[structure] no structure written", file=sys.stderr)
        return 1
    print(f"[structure] {len(written)} CIF file(s) generated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
